
import random
def get_random_songs(mood, song_data, num_songs=5):
    # Check if the mood is valid
    if mood not in song_data:
        return f"Sorry, we don't have songs for the mood '{mood}'."
    
    # Get the songs for the given mood
    songs = song_data[mood]
    
    # Randomly select `num_songs` from the list
    random_songs = random.sample(songs, min(num_songs, len(songs)))
    
    return random_songs

example_songs = {
    "Happy": [
       "Weightless – Marconi Union",
    "Clair de Lune – Claude Debussy",
    "Spiegel im Spiegel – Arvo Pärt",
    "Gymnopédie No. 1 – Erik Satie",
    "Watermark – Enya",
    "Adagio for Strings – Samuel Barber",
    "Moonlight Sonata – Ludwig van Beethoven",
    "Ave Maria – Franz Schubert",
    "Canon in D – Johann Pachelbel",
    "Imagine – John Lennon",
    "Hallelujah – Leonard Cohen",
    "Fields of Gold – Sting",
    "The Sound of Silence – Simon & Garfunkel",
    "What a Wonderful World – Louis Armstrong",
    "Yesterday – The Beatles",
    "Time After Time – Cyndi Lauper",
    "Blackbird – The Beatles",
    "Over the Rainbow – Israel Kamakawiwo'ole",
    "Let It Be – The Beatles",
    "Your Song – Elton John"
    ],
    "Calm": [
        "Lana Del Rey - Video Games",
    "Norah Jones - Don't Know Why",
    "John Mayer - Gravity",
    "Bon Iver - Skinny Love",
    "Fleet Foxes - White Winter Hymnal",
    "Sufjan Stevens - Should Have Known Better",
    "James Blake - Retrograde",
    "Simon & Garfunkel - The Sound of Silence",
    "The Paper Kites - Bloom",
    "Bill Withers - Ain't No Sunshine",
    "Angus & Julia Stone - Big Jet Plane",
    "Vance Joy - Riptide",
    "Iron & Wine - Flightless Bird, American Mouth",
    "Ben Howard - Keep Your Head Up",
    "Nick Drake - Pink Moon",
    "José González - Heartbeats",
    "The Lumineers - Ophelia",
    "Damien Rice - The Blower's Daughter",
    "Laura Marling - Ghosts",
    "Mazzy Star - Fade Into You"
    ],
    "Cool": [
    "Tame Impala - The Less I Know The Better",
    "Anderson .Paak - Come Down",
    "Mac Miller - Dang! (feat. Anderson .Paak)",
    "Tom Misch - It Runs Through Me (feat. De La Soul)",
    "Snoh Aalegra - I Want You Around",
    "Frank Ocean - Pink + White",
    "KAYTRANADA - You're the One (feat. Syd)",
    "Tyler, The Creator - See You Again (feat. Kali Uchis)",
    "Childish Gambino - Redbone",
    "Steve Lacy - N Side",
    "HONNE - Day 1 ◑",
    "Thundercat - Them Changes",
    "Alina Baraz - Electric (feat. Khalid)",
    "Daniel Caesar - Best Part (feat. H.E.R.)",
    "Miguel - Pineapple Skies",
    "Brent Faiyaz - Gravity (feat. Tyler, The Creator)",
    "Rhye - Open",
    "The Internet - Girl (feat. KAYTRANADA)",
    "Glass Animals - Gooey",
    "Joji - Sanctuary"],

    'background': [
        'Brian Eno - Ambient 1: Music for Airports',
        'Moby - Long Ambients 1: Calm. Sleep.',
        'Olafur Arnalds - Re:member',
        'Ludovico Einaudi - Divenire',
        'Max Richter - Sleep',
        'Explosions in the Sky - The Earth Is Not a Cold Dead Place',
        'Sigur Rós - ( )',
        'Tycho - Dive',
        'Nils Frahm - Spaces',
        'Jóhann Jóhannsson - Orphée',
        'A Winged Victory for the Sullen - A Winged Victory for the Sullen',
        'Bing & Ruth - Tomorrow Was the Golden Age',
        'Ryuichi Sakamoto - Async',
        'Keith Jarrett - The Köln Concert',
        'Gustavo Santaolalla - The Last of Us Soundtrack',
        'The Cinematic Orchestra - Ma Fleur',
        'Philip Glass - Glassworks',
        'Kaitlyn Aurelia Smith - EARS',
        'Jóhann Jóhannsson - Fordlândia'
    ],
    'film': [
        'Hans Zimmer - Time (Inception)',
        'Ennio Morricone - The Good, the Bad and the Ugly',
        'John Williams - Jurassic Park Theme',
        'Vangelis - Blade Runner Theme',
        'James Horner - Titanic Theme',
        'Michael Giacchino - Up Theme',
        'Alexandre Desplat - The Grand Budapest Hotel',
        'Howard Shore - The Lord of the Rings Theme',
        'Trent Reznor & Atticus Ross - The Social Network Soundtrack',
        'John Williams - Star Wars Theme',
        'Danny Elfman - Batman Theme',
        'Ludwig Göransson - Black Panther Theme',
        'Ramin Djawadi - Game of Thrones Theme',
        'Jerry Goldsmith - Planet of the Apes',
        'Philip Glass - The Hours Soundtrack',
        'M83 - Midnight City (Film Style)',
        'Max Richter - Arrival Soundtrack',
        'Lorne Balfe - Mission: Impossible Fallout Theme',
        'Giovanni Sollima - Violoncelles Vibrez'
    ],
    'melancholic': [
        'The Smiths - There Is a Light That Never Goes Out',
        'Radiohead - No Surprises',
        'Bon Iver - Holocene',
        'Billie Eilish - when the party’s over',
        'Sufjan Stevens - Fourth of July',
        'The National - I Need My Girl',
        'Damien Rice - 9 Crimes',
        'Jeff Buckley - Hallelujah',
        'Coldplay - The Scientist',
        'Elliott Smith - Miss Misery',
        'Lana Del Rey - Summertime Sadness',
        'Nick Drake - Pink Moon',
        'Angus & Julia Stone - Big Jet Plane',
        'Florence + The Machine - Never Let Me Go',
        'Adele - Someone Like You',
        'Lorde - Liability',
        'The Cure - Pictures of You',
        'Keaton Henson - You',
        'Bon Iver - Skinny Love',
        'Phoebe Bridgers - Motion Sickness'
    ],
    
    'melodic': [
        'The Beatles - Here Comes The Sun',
        'Fleetwood Mac - Dreams',
        'Adele - Rolling in the Deep',
        'Coldplay - Viva La Vida',
        'John Mayer - Gravity',
        'Tame Impala - The Less I Know The Better',
        'The Rolling Stones - Paint It Black',
        'Amy Winehouse - Back to Black',
        'Ed Sheeran - Thinking Out Loud',
        'Oasis - Wonderwall',
        'Vampire Weekend - A-Punk',
        'The Lumineers - Ho Hey',
        'Sam Smith - Stay With Me',
        'Shakira - Hips Don’t Lie',
        'Lady Gaga - Shallow',
        'Queen - Bohemian Rhapsody',
        'Sia - Chandelier',
        'U2 - With or Without You',
        'Shawn Mendes - Stitches',
        'Kings of Leon - Use Somebody'
    ],
    'children': [
        'The Beatles - Yellow Submarine',
        'The Lion King - Circle of Life',
        'Pharrell Williams - Happy',
        'Raffi - Baby Beluga',
        'Adele - Make You Feel My Love',
        'Disney - Let It Go (Frozen)',
        'Katy Perry - Roar',
        'Taylor Swift - Shake It Off',
        'The Monkees - I’m a Believer',
        'Jack Johnson - Upside Down',
        'Kidz Bop Kids - Old Town Road',
        'Bobby McFerrin - Don’t Worry Be Happy',
        'Elton John - Your Song',
        'The Jackson 5 - ABC',
        'Tina Turner - Simply the Best',
        'Queen - We Will Rock You',
        'Bill Withers - Lovely Day',
        'ABBA - Dancing Queen',
        'Harry Belafonte - Banana Boat Song',
        'The Muppets - Rainbow Connection'
    ],
    'relaxing': [
        'The xx - Intro',
        'Norah Jones - Come Away With Me',
        'John Mayer - Slow Dancing in a Burning Room',
        'Jack Johnson - Better Together',
        'Iron & Wine - Naked as We Came',
        'Sade - Smooth Operator',
        'Bill Evans - Blue in Green',
        'Simon & Garfunkel - The Sound of Silence',
        'Coldplay - Sparks',
        'Lana Del Rey - Video Games',
        'Sufjan Stevens - The Only Thing',
        'José González - Stay Alive',
        'Fleet Foxes - Helplessness Blues',
        'James Blake - Retrograde',
        'R.E.M. - Everybody Hurts',
        'The War on Drugs - Thinking of a Place',
        'Angel Olsen - Shut Up Kiss Me',
        'Glen Hansard - Falling Slowly',
        'Paul Simon - Graceland',
        'Sigur Rós - Hoppípolla'
    ],
    'meditative': [
        'Buddha Bar - Buddha Bar',
        'Anoushka Shankar - Land of Gold',
        'Deva Premal - Gayatri Mantra',
        'Kitaro - Silk Road',
        'Tibetian Singing Bowls - Meditation Sounds',
        'Brian Eno - Music for Films',
        'Snatam Kaur - Ong Namo',
        'John Cage - 4’33"',
        'Laraaji - Ambient 3: Day of Radiance',
        'George Harrison - My Sweet Lord',
        'Philip Glass - Music in 12 Parts',
        'Ravi Shankar - The Sounds of India',
        'Hiroshi Yoshimura - Green',
        'Vangelis - Blade Runner Blues',
        'Sitar - Ravi Shankar - Raga Jog',
        'Ludovico Einaudi - Ascolta',
        'Chihei Hatakeyama - The Color of Snow',
        'Steve Roach - Structures from Silence',
        'Lisa Gerrard - The Silver Tree',
        'Paul Horn - Inside the Great Pyramid'
    
    ],
    'documentary': [
        'David Bowie - The Rise and Fall of Ziggy Stardust',
        'The Rolling Stones - Gimme Shelter',
        'Neil Young - Heart of Gold',
        'Led Zeppelin - Stairway to Heaven',
        'Bob Dylan - The Times They Are A-Changin’',
        'Nina Simone - Feeling Good',
        'Bill Withers - Ain’t No Sunshine',
        'Johnny Cash - Hurt',
        'Simon & Garfunkel - Bridge Over Troubled Water',
        'The Beatles - Hey Jude',
        'Muddy Waters - Mannish Boy',
        'Marvin Gaye - What’s Going On',
        'Joni Mitchell - Big Yellow Taxi',
        'Tupac - Changes',
        'U2 - I Still Haven’t Found What I’m Looking For',
        'Bruce Springsteen - Born to Run',
        'Stevie Wonder - Superstition',
        'The Doors - Light My Fire',
        'Aretha Franklin - Respect',
        'Patti Smith - Because the Night'
    ],
    'emotional': [
        'Adele - Someone Like You',
        'Coldplay - Fix You',
        'Whitney Houston - I Will Always Love You',
        'Celine Dion - My Heart Will Go On',
        'John Legend - All of Me',
        'Ed Sheeran - Photograph',
        'The Fray - How to Save a Life',
        'Lewis Capaldi - Someone You Loved',
        'Christina Perri - A Thousand Years',
        'James Blunt - You’re Beautiful',
        'Taylor Swift - All Too Well',
        'Sarah McLachlan - Angel',
        'Elton John - Candle in the Wind',
        'Kelly Clarkson - Because of You',
        'Bruno Mars - When I Was Your Man',
        'The Script - The Man Who Can’t Be Moved',
        'Rihanna - Stay',
        'Alicia Keys - If I Ain’t Got You',
        'Florence + The Machine - Never Let Me Go',
        'A Great Big World - Say Something'
    ],
    'space': [
        'David Bowie - Space Oddity',
        'Pink Floyd - Astronomy Domine',
        'The Byrds - Mr. Spaceman',
        'Kraftwerk - Computer World',
        'Radiohead - Subterranean Homesick Alien',
        'Muse - Starlight',
        'The Rolling Stones - 2000 Light Years From Home',
        'Depeche Mode - Spacewalker',
        'The Flaming Lips - Do You Realize?',
        'Janelle Monáe - Cold War',
        'The Chemical Brothers - Galaxy Bounce',
        'Daft Punk - Voyager',
        'M83 - Midnight City',
        'LCD Soundsystem - Someone Great',
        'Tame Impala - Feels Like We Only Go Backwards',
        'The Killers - Spaceman',
        'Sufjan Stevens - Year of the Tiger',
        'John Lennon - Across the Universe',
        'Vangelis - Blade Runner (End Titles)',
        'Brian Eno - An Ending (Ascent)'
    ],

    "soundscape": [
        "Weightless – Marconi Union",
        "Ambient 1: Music for Airports – Brian Eno",
        "Spiegel im Spiegel – Arvo Pärt",
        "I Am Sitting in a Room – Alvin Lucier",
        "Music for 18 Musicians – Steve Reich",
        "The Disintegration Loops – William Basinski",
        "Rainforest – Craig Armstrong",
        "The Poet Acts – Philip Glass",
        "E2-E4 – Manuel Göttsching",
        "On the Nature of Daylight – Max Richter",
        "Deep Blue Day – Brian Eno",
        "The Sound of Silence – Simon & Garfunkel",
        "Hammock – Maybe They Will Sing for Us Tomorrow",
        "Phaedra – Tangerine Dream",
        "Biosphere – Substrata",
        "Live in the Realm of the Sun – Loscil",
        "After the Rain – Bill Evans",
        "Weightless Pt. 1 – Marconi Union",
        "Endless Summer – The Midnight"
    ],
    "slow": [
        "Hallelujah – Leonard Cohen",
        "Stay – Rihanna feat. Mikky Ekko",
        "Someone Like You – Adele",
        "Let Her Go – Passenger",
        "The Night We Met – Lord Huron",
        "All of Me – John Legend",
        "The Scientist – Coldplay",
        "Chasing Cars – Snow Patrol",
        "The A Team – Ed Sheeran",
        "Turning Tables – Adele",
        "I Will Always Love You – Whitney Houston",
        "Tears in Heaven – Eric Clapton",
        "I Don't Want to Miss a Thing – Aerosmith",
        "Just the Way You Are – Bruno Mars",
        "Say You Won't Let Go – James Arthur",
        "If I Ain't Got You – Alicia Keys",
        "Waiting for Love – Avicii",
        "I’m Not the Only One – Sam Smith",
        "Can’t Help Falling in Love – Elvis Presley",
        "Unchained Melody – The Righteous Brothers"
    ],
    "deep": [
        "In the Air Tonight – Phil Collins",
        "Hurt – Nine Inch Nails",
        "Teardrop – Massive Attack",
        "The Sound of Silence – Disturbed",
        "Black – Pearl Jam",
        "Everything In Its Right Place – Radiohead",
        "Mad World – Gary Jules",
        "Stairway to Heaven – Led Zeppelin",
        "The Unquiet Grave – The Unthanks",
        "The Killing Moon – Echo & The Bunnymen",
        "Breathe Me – Sia",
        "The National Anthem – Radiohead",
        "How to Save a Life – The Fray",
        "My Immortal – Evanescence",
        "No Surprises – Radiohead",
        "Creep – Radiohead",
        "All Along the Watchtower – The Jimi Hendrix Experience",
        "Runaway – Kanye West",
        "Under the Bridge – Red Hot Chili Peppers",
        "Mad World – Tears for Fears"
    ],
    "fun": [
        "Happy – Pharrell Williams",
        "Uptown Funk – Mark Ronson feat. Bruno Mars",
        "Can't Stop the Feeling! – Justin Timberlake",
        "Shake It Off – Taylor Swift",
        "Treasure – Bruno Mars",
        "I Gotta Feeling – The Black Eyed Peas",
        "Get Lucky – Daft Punk feat. Pharrell Williams",
        "Dynamite – BTS",
        "Party Rock Anthem – LMFAO",
        "Call Me Maybe – Carly Rae Jepsen",
        "Rolling in the Deep – Adele",
        "Gangnam Style – PSY",
        "On Top of the World – Imagine Dragons",
        "Don't Stop Believin' – Journey",
        "Roar – Katy Perry",
        "Let's Go – Calvin Harris feat. Ne-Yo",
        "Wake Me Up – Avicii",
        "Shut Up and Dance – WALK THE MOON",
        "I’m Yours – Jason Mraz",
        "Just Dance – Lady Gaga"
    ],
    "horror": [
        "The Exorcist Theme – Mike Oldfield",
        "Tubular Bells – Mike Oldfield",
        "The Shining Theme – Wendy Carlos & Rachel Elkind",
        "Halloween Theme – John Carpenter",
        "Nightmare on Elm Street Theme – Charles Bernstein",
        "Psycho Theme – Bernard Herrmann",
        "Jaws Theme – John Williams",
        "The Silence of the Lambs – Howard Shore",
        "Carrie Theme – Pino Donaggio",
        "The Thing Theme – Ennio Morricone",
        "The Ring Theme – Hans Zimmer",
        "Suspiria Theme – Goblin",
        "Requiem for a Dream – Clint Mansell",
        "The Others Theme – Alejandro Amenábar",
        "Rosemary's Baby Theme – Krzysztof Komeda",
        "The Babadook Theme – Jed Kurzel",
        "Hereditary Theme – Colin Stetson",
        "It Follows Theme – Disasterpeace",
        "Under the Skin Theme – Mica Levi",
        "Donnie Darko Theme – Michael Andrews"
    ],
    "nature": [
        "The Sound of Silence – Simon & Garfunkel",
        "Earth Song – Michael Jackson",
        "Take Me to Church – Hozier",
        "Big Yellow Taxi – Joni Mitchell",
        "Where the Green Grass Grows – Tim McGraw",
        "The River – Bruce Springsteen",
        "Wild World – Cat Stevens",
        "Circle of Life – Elton John",
        "America the Beautiful – Ray Charles",
        "Fields of Gold – Sting",
        "Down to the River to Pray – Alison Krauss",
        "Harvest Moon – Neil Young",
        "The Ocean – Led Zeppelin",
        "Black Earth – The Kills",
        "Sunshine on My Shoulders – John Denver",
        "The Rising – Bruce Springsteen",
        "Nature Boy – Nat King Cole",
        "Jungle Boogie – Kool & The Gang",
        "The Trees – Rush",
        "I Will Wait – Mumford & Sons"
    ],
    "funny": [
        "I'm Too Sexy – Right Said Fred",
        "Weird Al Yankovic – Amish Paradise",
        "The Duck Song – Bryant Oden",
        "Barbie Girl – Aqua",
        "Gangnam Style – PSY",
        "What Does the Fox Say? – Ylvis",
        "Yakety Sax – Boots Randolph",
        "The Hampster Dance – Hampton the Hampster",
        "Mahna Mahna – The Muppets",
        "Baby Shark – Pinkfong",
        "Bohemian Rhapsody – Queen (Parody Version)",
        "Never Gonna Give You Up – Rick Astley (Rickroll)",
        "Call Me Maybe – Carly Rae Jepsen (Parody Version)",
        "Take On Me – A-ha (Parody Version)",
        "I’m Gonna Be (500 Miles) – The Proclaimers",
        "Who Let the Dogs Out – Baha Men",
        "Cotton Eye Joe – Rednex",
        "Macarena – Los Del Rio",
        "Staying Alive – Bee Gees (Funny Covers)",
        "Rude – MAGIC! (Parody Version)"
    ],
    "happy": [
        "Happy – Pharrell Williams",
        "Can't Stop the Feeling! – Justin Timberlake",
        "Walking on Sunshine – Katrina & The Waves",
        "Uptown Funk – Mark Ronson feat. Bruno Mars",
        "Shake It Off – Taylor Swift",
        "Here Comes the Sun – The Beatles",
        "What a Wonderful World – Louis Armstrong",
        "Dancing Queen – ABBA",
        "Best Day of My Life – American Authors",
        "Good as Hell – Lizzo",
        "Feel Good Inc. – Gorillaz",
        "Don't Stop Me Now – Queen",
        "Firework – Katy Perry",
        "On Top of the World – Imagine Dragons",
        "Just the Way You Are – Bruno Mars",
        "I'm Yours – Jason Mraz",
        "Stronger (What Doesn't Kill You) – Kelly Clarkson",
        "Roar – Katy Perry",
        "I Gotta Feeling – The Black Eyed Peas",
        "Call Me Maybe – Carly Rae Jepsen"
    ],
    "positive": [
        "Eye of the Tiger – Survivor",
        "Don't Stop Believin' – Journey",
        "Happy – Pharrell Williams",
        "Stronger (What Doesn't Kill You) – Kelly Clarkson",
        "Fight Song – Rachel Platten",
        "On Top of the World – Imagine Dragons",
        "Good Life – OneRepublic",
        "Walking on Sunshine – Katrina & The Waves",
        "Rise Up – Andra Day",
        "Survivor – Destiny's Child",
        "Firework – Katy Perry",
        "Shake It Off – Taylor Swift",
        "Ain't No Mountain High Enough – Marvin Gaye & Tammi Terrell",
        "Can't Stop the Feeling! – Justin Timberlake",
        "Just the Way You Are – Bruno Mars",
        "Don't Worry, Be Happy – Bobby McFerrin",
        "Happy Together – The Turtles",
        "Here Comes the Sun – The Beatles",
        "All Star – Smash Mouth",
        "I'm Still Standing – Elton John"
    ],
    "sad": [
        "Tears in Heaven – Eric Clapton",
        "Someone Like You – Adele",
        "The Night We Met – Lord Huron",
        "Let Her Go – Passenger",
        "The Scientist – Coldplay",
        "Chasing Cars – Snow Patrol",
        "Fix You – Coldplay",
        "All I Want – Kodaline",
        "I Will Always Love You – Whitney Houston",
        "I’m Not the Only One – Sam Smith",
        "Hurt – Nine Inch Nails",
        "Skinny Love – Bon Iver",
        "The A Team – Ed Sheeran",
        "The Blower's Daughter – Damien Rice",
        "Say Something – A Great Big World feat. Christina Aguilera",
        "My Heart Will Go On – Celine Dion",
        "Unchained Melody – The Righteous Brothers",
        "Breathe Me – Sia",
        "When We Were Young – Adele",
        "Mad World – Gary Jules"
    ]
}


